/**
 * Chettinad Heritage Digital Gallery Data Registry
 * Configured with your exact local image paths
 */

const GALLERY_FOLDERS = [
    {
        id: "architectural-heritage",
        folderName: "architectural heritage",
        title: "Architectural Heritage & Artefacts",
        images: [
            "architectural heritage/Traditional Keys and Devotional Figurines.JPG",
            "architectural heritage/Vintage Ceramic and Glassware Collection.JPG",
            "architectural heritage/Traditional Painted Wooden Lion.JPG",
            "architectural heritage/Vintage Travel Cases.JPG",
            "architectural heritage/Traditional storage boxes.JPG",
            "architectural heritage/Devotional and Cultural Figurine Collection.JPG",
            "architectural heritage/Central Courtyard of a Chettinad Mansion.JPG",
                        "architectural heritage/Traditional wood carving.JPG",
            "architectural heritage/Intricate wood carvings.JPG",
                        "architectural heritage/Chandeliers.jpg",
            "architectural heritage/Chandeliers- bottom view.jpg",
            "architectural heritage/chettinad palace- 2.jpg",
            "architectural heritage/Chettinad Palace interior-1.jpg",
            "architectural heritage/chettinad palace interior-2.jpg",
            "architectural heritage/chettinad palace interior-3 wood carvings.jpg",
            "architectural heritage/chettinad palace-1.jpg",
            "architectural heritage/chettinad palace-3.jpg",
            "architectural heritage/Traditional lamp.jpg",
            "architectural heritage/Saratha Vilas Reception.jpg",
            "architectural heritage/Saratha Vilas Interior.JPG",
                            "architectural heritage/Wood carvings.jpg"
        ]
    },
    {
        id: "handicraft-shop",
        folderName: "Handicraft shop",
        title: "Handicraft Shop",
        images: [
            "Handicraft shop/C1144T01.JPG",
            "Handicraft shop/C1145T01.JPG",
            "Handicraft shop/C1146T01.JPG",
            "Handicraft shop/C1147T01.JPG",
            "Handicraft shop/C1148T01.JPG",
            "Handicraft shop/C1149T01.JPG",
            "Handicraft shop/C1150T01.JPG",
            "Handicraft shop/C1151T01.JPG",
            "Handicraft shop/C1152T01.JPG",
            "Handicraft shop/C1153T01.JPG",
            "Handicraft shop/C1154T01.JPG",
            "Handicraft shop/C1155T01.JPG",
            "Handicraft shop/C1156T01.JPG",
            "Handicraft shop/C1157T01.JPG",
            "Handicraft shop/C1158T01.JPG",
            "Handicraft shop/C1159T01.JPG"
        ]
    },
    {
        id: "products-and-dye-making",
        folderName: "Kottan Basket Making",
title: "Kottan Basket Making",
        images: [
            "products and dye making/C1246T01.JPG",
            "products and dye making/C1247T01.JPG",
            "products and dye making/C1248T01.JPG",
            "products and dye making/C1249T01.JPG",
            "products and dye making/C1250T01.JPG",
            "products and dye making/C1251T01.JPG",
            "products and dye making/C1252T01.JPG",
            "products and dye making/C1253T01.JPG",
            "products and dye making/C1254T01.JPG",
            "products and dye making/C1316T01.JPG",
            "products and dye making/C1317T01.JPG",
            "products and dye making/C1318T01.JPG",
            "products and dye making/C1319T01.JPG",
            "products and dye making/C1320T01.JPG",
            "products and dye making/C1321T01.JPG",
            "products and dye making/C1322T01.JPG",
            "products and dye making/C1323T01.JPG",
            "products and dye making/C1324T01.JPG",
            "products and dye making/C1325T01.JPG",
            "products and dye making/C1326T01.JPG",
            "products and dye making/C1327T01.JPG",
            "products and dye making/C1328T01.JPG",
            "products and dye making/C1329T01.JPG",
            "products and dye making/C1330T01.JPG",
            "products and dye making/C1331T01.JPG",
            "products and dye making/C1332T01.JPG",
            "products and dye making/C1333T01.JPG",
            "products and dye making/C1334T01.JPG",
            "products and dye making/C1335T01.JPG",
            "products and dye making/C1336T01.JPG",
            "products and dye making/C1337T01.JPG",
            "products and dye making/C1338T01.JPG",
            "products and dye making/C1339T01.JPG",
            "products and dye making/C1340T01.JPG",
            "products and dye making/C1341T01.JPG",
            "products and dye making/C1342T01.JPG",
            "products and dye making/C1343T01.JPG",
            "products and dye making/C1344T01.JPG",
            "products and dye making/C1345T01.JPG",
            "products and dye making/C1346T01.JPG",
            "products and dye making/C1347T01.JPG",
           "products and dye making/C1350T01.JPG",
            "products and dye making/C1351T01.JPG",
            "products and dye making/C1352T01.JPG",
            "products and dye making/C1353T01.JPG",
            "products and dye making/C1354T01.JPG",
            "products and dye making/C1355T01.JPG",
            "products and dye making/C1356T01.JPG",
            "products and dye making/C1357T01.JPG",
            "products and dye making/C1358T01.JPG",
            "products and dye making/C1359T01.JPG",
            "products and dye making/C1360T01.JPG",
            "products and dye making/C1361T01.JPG",
            "products and dye making/C1362T01.JPG",
            "products and dye making/C1363T01.JPG",
            "products and dye making/C1364T01.JPG",
            "products and dye making/C1365T01.JPG",
            "products and dye making/C1366T01.JPG",
            "products and dye making/C1367T01.JPG",
            "products and dye making/C1368T01.JPG",
            "products and dye making/C1369T01.JPG",
            "products and dye making/C1370T01.JPG",
            "products and dye making/C1371T01.JPG",
            "products and dye making/C1372T01.JPG",
            "products and dye making/C1373T01.JPG",
            "products and dye making/C1374T01.JPG",
            "products and dye making/C1375T01.JPG",
            "products and dye making/C1377T01.JPG",
            "products and dye making/C1380T01.JPG",
        
        
           
        ]
    },
    {
        id: "tile-making",
        folderName: "tile making",
        title: "Tile Making",
        images: [
            "tile making/1 (2).png",
            "tile making/1 (3).png",
            "tile making/1 (4).png",
            "tile making/1 (7).png",
            "tile making/1 (8).png",
            "tile making/1 (9).png",
            "tile making/1 (10).png",
            "tile making/1 (11).png",
            "tile making/1 (12).png",
            "tile making/1 (13).png",
            "tile making/Athangudi tiles.png",
            "tile making/R0010030.jpg",
            "tile making/Stages of Athangudi tile making-1.png",
            "tile making/Stages of Athangudi tile making-2.png",
            "tile making/Stages of Athangudi tile making-3.png",
            "tile making/Stages of Athangudi tile making-4.png",
            "tile making/Stages of Athangudi tile making-5.png",
            "tile making/t3.png",
            "tile making/t4.png",
            "tile making/t5.png",
            "tile making/Tile Curing Process.png",
            "tile making/Tiles after laying process.png"
        ]
    }
];